[package]
name="cripes"
version="0.0.1"
authors=["Collin J. Sutton"]

[lib]
name="cripes"
path="src/lib.rs"

[[test]]
name="test"
path="test/mod.rs"

[dependencies]
regex-syntax = "*"
num = "*"
smallvec = "*"
